### ISSUE TITLE
Add gitbook links

### ISSUE THREAD

**Issue by yidoyoon** [yidoyoon/resume-on-aws#10]
### Category

Documentation

### Description

Document everything you've learned, everything you've done while working on the project, and write it in your Gitbook. And add a link to the repository.

### TODOs

- [ ] Manual approach(English resume distribution process via AWS dashboard)
- [ ] IaC approach(English resume distribution process via AWS CloudFormation, SAM)
- [ ] Troubleshootings while working on the project
